version: 2.1
jobs:
   print_FADY:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "Say World"
          command: echo $FADY
workflows:
  say-hello-workflow:
    jobs:
      - print_FADY
           